version: '3.9'

services:
  crn-product-api:
    container_name: crn-product-api
    build:
      context: .
      dockerfile: src/CRN.Product.Api/Dockerfile

    ports:
      - "8080:8080"

    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_URLS: http://+:8080

      ConnectionStrings__DefaultConnection: "Server=sqlserver;Database=KBProductData;User Id=KishorBaradkarSQLAdmin;Password=Jimny4x4@#;TrustServerCertificate=True;Encrypt=False"

    depends_on:
      - sqlserver

    restart: unless-stopped

  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest

    container_name: crn-sqlserver

    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: "YourStrong@Passw0rd"

    ports:
      - "1433:1433"

    volumes:
      - sql_data:/var/opt/mssql

    restart: unless-stopped

volumes:
  sql_data:s